### ISSUE TITLE
按说明配置完后，提示“Component is not found in path "pages/plugin:/wx9d4d4ffa781ff3ac/wxparser" ”

### ISSUE THREAD

**Issue by samawong** [ifanrx/wxParser-plugin#2]
按照说明配置完后，提示“Component is not found in path "pages/plugin:/wx9d4d4ffa781ff3ac/wxparser" ”，使用的是wepy开发框架写的代码，感觉是路径不对，但是按照生成的json文件看着都和说明文档里的一致，我应该如何去修正？请提供个思路，谢谢

**Comment by xxrt** [comment]
也遇到了一样的错误

app.json：
`"plugins": {
    "wxparserPlugin": {
      "version": "0.1.0",
      "provider": "wx9d4d4ffa781ff3ac"
    }
  },`

引用：
`"usingComponents": {
    "wxparser": "plugin://wxparserPlugin/wxparser",
    "gift": "/pages/template/component_gift",
    "getCards": "/pages/template/getCards"
  }`

报错：
`VM18029:1 jsEnginScriptError
Component is not found in path "pages/tabbar/plugin:/wx9d4d4ffa781ff3ac/wxparser" (using by "pages/tabbar/plat-home")
Error: Component is not found in path "pages/tabbar/plugin:/wx9d4d4ffa781ff3ac/wxparser" (using by "pages/tabbar/plat-home")
    at e (http://127.0.0.1:64318/appservice/__dev__/WAService.js:13:29011)
    at e (http://127.0.0.1:64318/appservice/__dev__/WAService.js:13:29163)
    at W (http://127.0.0.1:64318/appservice/__dev__/WAService.js:14:3348)
    at Object.t.addView (http://127.0.0.1:64318/appservice/__dev__/WAService.js:14:4358)
    at Function.value (http://127.0.0.1:64318/appservice/__dev__/WAService.js:15:28964)
    at B (http://127.0.0.1:64318/appservice/__dev__/WAService.js:15:7087)
    at H (http://127.0.0.1:64318/appservice/__dev__/WAService.js:15:9522)
    at q (http://127.0.0.1:64318/appservice/__dev__/WAService.js:15:9788)
    at Function.<anonymous> (http://127.0.0.1:64318/appservice/__dev__/WAService.js:15:12171)
    at http://127.0.0.1:64318/appservice/__dev__/WAService.js:15:17917`

**Comment by YaoKaiLun** [comment]
微信开发者工具中用的基础库有要大于 1.9.2 吗？

**Comment by wzxm** [comment]
WAService.js:3 jsEnginScriptError
Component is not found in path "plugin://wxparserPlugin/wxParser" (using by "pages/forumDetail")
Error: Component is not found in path "plugin://wxparserPlugin/wxParser" (using by "pages/forumDetail")
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:8607)
    at e (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:8759)
    at z (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:16619)
    at Object.t.addView (http://127.0.0.1:9973/appservice/__dev__/WAService.js:15:17678)
    at Function.value (http://127.0.0.1:9973/appservice/__dev__/WAService.js:17:13017)
    at B (http://127.0.0.1:9973/appservice/__dev__/WAService.js:16:22862)
    at L (http://127.0.0.1:9973/appservice/__dev__/WAService.js:16:24148)
    at G (http://127.0.0.1:9973/appservice/__dev__/WAService.js:16:25469)
    at Function.<anonymous> (http://127.0.0.1:9973/appservice/__dev__/WAService.js:16:27935)
    at http://127.0.0.1:9973/appservice/__dev__/WAService.js:17:1968

我也同样报了这个错误，基础库是 1.9.9
