### ISSUE TITLE
Cannot read property 'version' of undefined 是怎么回事？

### ISSUE THREAD

**Issue by voglinde** [ifanrx/wxParser-plugin#27]
按使用指南：

```
在需要使用到该插件的小程序页面的 json 配置文件中，做如下配置：
{
  "usingComponents": {
    "wxparser": "plugin://wxparserPlugin/wxparser"
  }
}
```

这样设置之后报错：

```
jsEnginScriptError
Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at w (http://127.0.0.1:63969/appservice/__dev__/WAService.js:17:23528)
    at e.value (http://127.0.0.1:63969/appservice/__dev__/WAService.js:17:25375)
    at http://127.0.0.1:63969/appservice/__dev__/WAService.js:17:26330
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:63969/appservice/__dev__/WAService.js:17:26302)
    at e.value (http://127.0.0.1:63969/appservice/__dev__/WAService.js:17:21596)
    at v._advancedCreate (http://127.0.0.1:63969/appservice/__dev__/WAService.js:16:9171)
    at Object.v.create [as createElement] (http://127.0.0.1:63969/appservice/__dev__/WAService.js:16:10577)
    at le (http://127.0.0.1:63969/appservice/__dev__/WAService.js:17:16625)
    at Object.i.addView (http://127.0.0.1:63969/appservice/__dev__/WAService.js:17:17734)


```
请教下是怎么回事？

**Comment by bestyxie** [comment]
这个不是我们插件的问题，是微信基础库的，可以切换一下基础库，参考https://developers.weixin.qq.com/community/develop/doc/00060a413a4678ccb1d6eddb45b400
